# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: registry.gitlab.com/cin/custom-images:eclipse-temurin-git-17-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

services:
  - name: docker:dind-stable
    alias: localhost
    command: ["--tls=false"]

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - release

build:
  stage: build
  tags:
    - gitlab-org-docker
  script:
    - ./gradlew --build-cache build
  artifacts:
    reports:
      junit: build/test-results/test/*.xml
    paths:
      - $CI_PROJECT_DIR/build/reports/test

release:
  stage: release
  tags:
    - gitlab-org-docker
  before_script:
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh ke
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email "gitlab-ci@ingenhaag-tech.de"
    - git config --global user.name "Christian Ingenhaag"
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git status
  script:
    - ./gradlew release -Prelease.useAutomaticVersion=true --stacktrace
  only:
    - main
