# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: registry.gitlab.com/cin/custom-images:eclipse-temurin-git-17-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - release

build:
  stage: build
  script: ./gradlew --build-cache build
  artifacts:
    reports:
      junit: build/test-results/test/*.xml
    paths:
      - build/reports/test
      - build/libs/*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

release:
  stage: release
  services:
  - docker:dind
  script:
    - ./gradlew release -Prelease.useAutomaticVersion=true
  only:
    - main
