
getmydeck:
  steam:
    reservation-start: 1626454800

  deckbot:
    scheduler:
      enabled: ${DECKBOT_SCHEDULER_ENABLED:false}
    google-api-key: ***REMOVED***
    sheet-id: 1ZaKncig9fce7K0sr1f-E2_sgLH1HuKQ-q3k7clPMOCs
    sheet-data-location: "deckbot!A1:C9"
    base-url: https://sheets.googleapis.com/v4/spreadsheets
    url: "${getmydeck.deckbot.base-url}/${getmydeck.deckbot.sheet-id}/values/${getmydeck.deckbot.sheet-data-location}?key=${getmydeck.deckbot.google-api-key}"

  persistence:
    path: ${DECKBOT_DATA_PATH:classpath:deckbot-data.json}
    create-if-not-exists: ${DECKBOT_DATA_PATH_CREATE_IF_NOT_EXISTS:false}

spring:
  data:
    mongodb:
      uri: ${DECKBOT_MONGODB_URI:mongodb://getmydeck:password123@localhost:27017/getmydeck}
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  server:
    port: 8081
