
steam:
  reservation-start: 1626454800

deckbot:
  google-api-key: ***REMOVED***
  sheet-id: 1ZaKncig9fce7K0sr1f-E2_sgLH1HuKQ-q3k7clPMOCs
  sheet-data-location: "deckbot!A1:C9"
  base-url: https://sheets.googleapis.com/v4/spreadsheets
  url: "${deckbot.base-url}/${deckbot.sheet-id}/values/${deckbot.sheet-data-location}?key=${deckbot.google-api-key}"

persistence:
  enabled: {DECKBOT_DATA_ENABLED:false}
  path: ${DECKBOT_DATA_PATH:classpath:deckbot-data.json}
  create-if-not-exists: ${DECKBOT_DATA_PATH_CREATE_IF_NOT_EXISTS:false}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  server:
    port: 8081