getmydeck:
  steam:
    reservation-start: 1626454800

  deckbot:
    scheduler:
      enabled: ${DECKBOT_SCHEDULER_ENABLED:true}
    google-api-key: ${DECKBOT_GOOGLE_SHEET_APIKEY:dummy}
    sheet-id: ${DECKBOT_GOOGLE_SHEET_ID:dummy}
    sheet-data-location: "deckbot!A1:C9"
    base-url: https://sheets.googleapis.com/v4/spreadsheets
    url: "${getmydeck.deckbot.base-url}/${getmydeck.deckbot.sheet-id}/values/${getmydeck.deckbot.sheet-data-location}?key=${getmydeck.deckbot.google-api-key}"

springdoc:
  api-docs:
    path: /api/openapi-docs

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  data:
    mongodb:
      uri: ${DECKBOT_MONGODB_URI:mongodb://getmydeck:password123@localhost:27017/getmydeck}
      auto-index-creation: true

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  server:
    port: 8081
