
steam:
  reservation-start: 1626454800
  last-static-update: 1654193119
  last-shipments:
    US:
      S64: 1626471512
      S256: 1626466837
      S512: 1626457290
    UK:
      S64: 1626622497
      S256: 1626460034
      S512: 1626456342
    EU:
      S64: 1626742716
      S256: 1626639335
      S512: 1626628529

deckbot:
  google-api-key: ***REMOVED***
  sheet-id: 1ZaKncig9fce7K0sr1f-E2_sgLH1HuKQ-q3k7clPMOCs
  sheet-data-location: "deckbot!A1:C9"
  base-url: https://sheets.googleapis.com/v4/spreadsheets
  url: "${deckbot.base-url}/${deckbot.sheet-id}/values/${deckbot.sheet-data-location}?key=${deckbot.google-api-key}"

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  server:
    port: 8081