name: Build branch

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build with Gradle
        env:
          GH_TOKEN: '${{secrets.GITHUB_TOKEN}}'
          GH_BRANCH: '${{github.ref.name}}'
        run: ./gradlew release -Prelease.useAutomaticVersion=true --stacktrace